### ISSUE TITLE
update.sh doesn't work with cron (PGP-related)

### ISSUE THREAD

**Issue by soonhokong** [leanprover/ppa-updater#2]
@leodemoura explained the issue as follows:

...
However, it fails when I try to execute it using cron. The problem is that there is no tty, and pgp fails because of that. I read that the default solution is to provide the option “--no-tty” to pgp. However, we don’t call it directly. I believe it is indirectly called by the debuild tool. So, I didn’t find any way to do it. I also tried to simulate a fake tty using the “script -c" command, but it also didn’t work.
...

**Comment by leodemoura** [comment]
I'm planning to use the following work around.
1- Ubuntu supports "Startup applications". I will setup one of them to create a terminal and start the bash script that updates the PPA. 
2- The script will contain an "infinite loop" and will invoke `sleep 1d` in each iteration.

This is a "poor's man" cron job. This is not perfect, but at least I don't have to keep manually updating the PPA. I will still have to startup the VM and login from time to time, but it is slightly better.

**Comment by soonhokong** [comment]
I see. Let's keep this solution until we find a better one.

**Comment by soonhokong** [comment]
@leodemoura, I just tested it with `crontab` and it seems it's working without PGP key problem. If you don't mind, I can run this daily cronjob on my machine.

**Comment by leodemoura** [comment]
Thanks!
