### ISSUE TITLE
lean : Depends: libstdc++-4.8-dev but it is not installable

### ISSUE THREAD

**Issue by soonhokong** [leanprover/ppa-updater#3]
Problem
-----------

On a fresh Ubuntu-12.04.05 installation, following the instruction for using PPA fails as follows:

```bash
$sudo apt-get install lean
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lean : Depends: libstdc++-4.8-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
```

This is due to the `libstdc++-4.8-dev` dependencies. 

A solution
--------------

Adding `ppa:ubuntu-toolchain-r/test` to the system is a solution:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
```

However, I'm not sure that this is the best we can do. @leodemoura, please let me know if you have any better idea.

For now, I'll update http://leanprover.github.io/download page with the above solution.

**Comment by soonhokong** [comment]
> For now, I'll update http://leanprover.github.io/download page with the above solution.

Done.

**Comment by leodemoura** [comment]
I just tested the new installation instructions on a fresh Ubuntu 12.04 installation.
http://leanprover.github.io/download/ubuntu12inst

Everything worked smoothly. After executing the `apt` commands, I could start Lean using `leanemacs` without performing any local configuration.

I think the Windows, Ubuntu 14 and 12 are pretty good. The only problematic case is OSX.

**Comment by soonhokong** [comment]
> The only problematic case is OSX.

I see. Let me close this one.
